spring.application.name=notes
#spring.security.user.name=user
#spring.security.user.password=user123
spring.datasource.url=jdbc:mysql://localhost:3306/securenotes
spring.datasource.username=root
spring.datasource.password=Chi@ntu$143
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.security=DEBUG
spring.app.jwtSecret=mySecretKey123912738jfjfuewhfkdnsfiehgangiuaegkjabdsiagai
spring.app.jwtExpirationMs=172800000
# 172800000--2 days in millseconds

# email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rohithpottabathini@gmail.com
spring.mail.password=vamlfpypnaalboob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


frontend.url=http://localhost:3000
# Github OAuth2 Configurations
spring.security.oauth2.client.registration.github.client-id=Ov23liamHEiu8FkQQtCF
spring.security.oauth2.client.registration.github.client-secret=3e6e69dfce555c5d9acd52f02707fa8af4ed3543
spring.security.oauth2.client.registration.github.scope=read:user,user:email
